name_prefix: "dev-vpc"

vpc_cidr: "10.0.0.0/16"

public_subnets:
  - cidr: "10.0.1.0/24"
    az: "ap-northeast-1a"
    name: "dev-public-1"
  - cidr: "10.0.2.0/24"
    az: "ap-northeast-1c"
    name: "dev-public-2"

private_subnets:
  - cidr: "10.0.11.0/24"
    az: "ap-northeast-1a"
    name: "dev-private-1"
  - cidr: "10.0.12.0/24"
    az: "ap-northeast-1c"
    name: "dev-private-2"
