project_id: "modern-app-dev"
network_name: "dev-vpc"

subnets:
  - name: "dev-public-1"
    ip_cidr_range: "10.0.1.0/24"
    region: "us-central1"
  - name: "dev-private-1"
    ip_cidr_range: "10.0.11.0/24"
    region: "us-central1"

firewall_tags:
  ssh: "dev-ssh"
  web: "dev-web"
