project_id: "modern-app-dev"
region: "us-central1"

landingzone:
  enable_default_network_cleanup: true
  enable_oslogin_enforce: true
  enable_audit_logging: true
  enabled_services:
    - compute.googleapis.com
    - iam.googleapis.com
    - cloudresourcemanager.googleapis.com
    - logging.googleapis.com
    - servicemanagement.googleapis.com
