project_id: "modern-app-dev"
name_prefix: "dev-compute"
zone: "us-central1-a"
machine_type: "e2-medium"
image: "ubuntu-2204-lts"

network_self_link: "projects/modern-app-dev/global/networks/dev-vpc"
subnet_self_link: "projects/modern-app-dev/regions/us-central1/subnetworks/dev-private-1"

metadata:
  ssh_keys:
    - "devops:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCquf7APpVdazv1xC5loENKQyWrOOI+yeP13jsMoPTFr/7A1za2cdHVv75D4f0ZePuvxi+3S4Nf5eCn5xsnzuvnvV3rxJ7bC3SbgsVA4STpdkElWJxz/TcgE7kMWSyGfNa5+07Ljjq2+g7fqFfEGP7x3+NFuTIvdy7OOhHPK29m8OIgHtO+X7NWDzSIe4lmxOfo9hQLU5qkWWmY+FXuDLO06mu5a1ruSlG4/lKQ77lr6E5k6I7dpFIlzPzCYcLOQDZ80GLk6e2ukgIFzOxplnnmnIBm9saKzNhxZ9V0sbOYu4lWuxpkzrQJBSyiR7+A8mE4xboz85vPX5dHRXc5bBLF6oVT/GH1+8eMqNygwdqbSKBzR5V1Z1LvJfHpJQmmH8T0U/ax7Rz1tfJbdSWJ9sFvVOuNKs1oo0WM6E/j1MMmwzZg1JYwl6GDaFpyUp92wjSyFcJTNfn1Fx5t8o0HpcQNVdLMeOHlqlPRkYfED1x4hlEZJu0fD/8IvcaUsdluyMFSxhE= devops@example.com"

boot_disk_gb: 30
tags:
  - dev-ssh
  - dev-web

firewall_rules:
  - name: "dev-ssh"
    direction: ingress
    ranges:
      - "0.0.0.0/0"
    protocols:
      tcp: [22]
    target_tags:
      - dev-ssh
  - name: "dev-web"
    direction: ingress
    ranges:
      - "0.0.0.0/0"
    protocols:
      tcp: [80, 443]
    target_tags:
      - dev-web
